# Generated by Django 2.2.13 on 2020-11-16 01:30

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone
import location_field.models.plain


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(default='Belgrade', max_length=255)),
                ('location', location_field.models.plain.PlainLocationField(default='44.815971791260516,20.46053409576416', max_length=63)),
                ('show_map', models.BooleanField()),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('public', models.BooleanField()),
            ],
            options={
                'db_table': 'events',
            },
        ),
    ]
