# Generated by Django 2.2.13 on 2020-11-24 14:22

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, default='44.815971791260516,20.46053409576416', max_length=63),
        ),
    ]
