# Generated by Django 5.2.17 on 2026-09-12 23:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_auto_20201124_1522"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
