# Generated by Django 2.2.13 on 2020-11-24 15:10

from django.db import migrations, models
import core.helpers
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20201124_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to=core.helpers.RandomFileName('static/images/')),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
