# Generated by Django 5.2.17 on 2026-09-12 23:02

import apps.core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0002_auto_20201124_1610"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="file",
            field=models.ImageField(
                upload_to=apps.core.helpers.RandomFileName("images/")
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
