# Generated by Django 5.2.17 on 2026-09-12 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0001_initial"),
    ]

    operations = [
        # Chapter changes
        migrations.AddField(
            model_name='chapter',
            name='is_starting_chapter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chapter',
            name='is_terminal',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='connections',
        ),
        
        # Choice changes
        migrations.RenameField(
            model_name='choice',
            old_name='name',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='money',
            new_name='money_cost',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='energy',
            new_name='energy_cost',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='node',
            new_name='from_chapter',
        ),
        migrations.AddField(
            model_name='choice',
            name='to_chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices_to', to='story.chapter', default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='choice',
            name='from_chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices_from', to='story.chapter'),
        ),
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together={('from_chapter', 'to_chapter', 'text')},
        ),

        # ReaderUser changes
        migrations.RenameField(
            model_name='readeruser',
            old_name='current_node',
            new_name='current_chapter',
        ),
        migrations.AlterField(
            model_name='readeruser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='reader_users', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='readeruser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='reader_users', to='auth.permission'),
        ),

        # Delete ChapterConnection
        migrations.DeleteModel(
            name='ChapterConnection',
        ),

        # New model ChoiceHistory
        migrations.CreateModel(
            name='ChoiceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.choice')),
                ('from_chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_from', to='story.chapter')),
                ('to_chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_to', to='story.chapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_history', to='story.readeruser')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
