# Generated by Django 5.2.17 on 2026-09-12 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("story", "0002_fix_story_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choice",
            name="energy_cost",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="choice",
            name="money_cost",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="readeruser",
            name="current_chapter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="story.chapter",
            ),
        ),
    ]
