# Generated by Django 5.2.17 on 2026-09-12 23:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0003_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="about",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
