# Generated by Django 2.2.13 on 2020-11-16 01:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', ckeditor.fields.RichTextField()),
                ('public', models.BooleanField()),
                ('language', models.CharField(default='eng', max_length=3)),
                ('image', models.ImageField(blank=True, default=None, upload_to='static/images/')),
                ('date_published', models.DateTimeField(verbose_name='date published')),
            ],
            options={
                'verbose_name_plural': 'news',
                'db_table': 'news',
            },
        ),
    ]
