# Generated by Django 2.2.8 on 2020-06-14 23:40

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('text', ckeditor.fields.RichTextField()),
                ('next', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forward', to='nodes.Node')),
                ('prev', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='back', to='nodes.Node')),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceNode',
            fields=[
                ('node_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nodes.Node')),
                ('high', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='good', to='nodes.ChoiceNode')),
            ],
            bases=('nodes.node',),
        ),
        migrations.AddField(
            model_name='node',
            name='nonlinear',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nonelinear_switch', to='nodes.ChoiceNode'),
        ),
        migrations.AddField(
            model_name='choicenode',
            name='linear',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linear_switch', to='nodes.Node'),
        ),
        migrations.AddField(
            model_name='choicenode',
            name='low',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bad', to='nodes.ChoiceNode'),
        ),
        migrations.AddField(
            model_name='choicenode',
            name='mid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='neutral', to='nodes.ChoiceNode'),
        ),
    ]
