# Generated by Django 5.0.4 on 2025-06-21 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="readeruser",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="choice",
            name="energy",
        ),
        migrations.RemoveField(
            model_name="choice",
            name="money",
        ),
        migrations.RemoveField(
            model_name="choice",
            name="node",
        ),
        migrations.RemoveField(
            model_name="readeruser",
            name="current_node",
        ),
        migrations.RemoveField(
            model_name="readeruser",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="readeruser",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="readeruser",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="readeruser",
            name="user_permissions",
        ),
        migrations.AddField(
            model_name="chapter",
            name="is_terminal",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="choice",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="choice",
            name="energy_cost",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="choice",
            name="from_chapter",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="choices",
                to="story.chapter",
            ),
        ),
        migrations.AddField(
            model_name="choice",
            name="money_cost",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="choice",
            name="to_chapter",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incoming_choices",
                to="story.chapter",
            ),
        ),
        migrations.AddField(
            model_name="readeruser",
            name="current_chapter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="story.chapter",
            ),
        ),
        migrations.AddField(
            model_name="readeruser",
            name="session_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="chapterconnection",
            name="from_chapter",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="from_chapter_connections",
                to="story.chapter",
            ),
        ),
        migrations.AlterField(
            model_name="chapterconnection",
            name="to_chapter",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="to_chapter_connections",
                to="story.chapter",
            ),
        ),
        migrations.AlterField(
            model_name="readeruser",
            name="date_joined",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="readeruser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="readeruser",
            name="first_name",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="readeruser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="readeruser",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="readeruser",
            name="last_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="readeruser",
            name="password",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="readeruser",
            name="username",
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.CreateModel(
            name="UserProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="story.chapter"
                    ),
                ),
                (
                    "choice_made",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="story.choice",
                    ),
                ),
                (
                    "reader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="story.readeruser",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
