# Generated by Django 2.2.13 on 2020-11-24 15:10

from django.db import migrations, models
import core.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(upload_to=core.helpers.RandomFileName('static/images/')),
        ),
    ]
