# Generated by Django 2.2.13 on 2020-11-16 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('code', models.CharField(max_length=12)),
                ('release_date', models.DateField(verbose_name='release date')),
                ('public', models.BooleanField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.Image')),
            ],
            options={
                'db_table': 'albums',
            },
        ),
    ]
