# Generated by Django 2.2.8 on 2020-05-13 22:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
