# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-02 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('code', models.CharField(max_length=12)),
                ('release_date', models.DateTimeField(verbose_name='release date')),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow.Image')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('public', models.BooleanField(default=True)),
                ('date_posted', models.DateTimeField(verbose_name='date posted')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('package', models.TextField()),
                ('date_ordered', models.DateTimeField(verbose_name='date ordered')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='language',
            field=models.CharField(default='eng', max_length=3),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='flow.Post'),
        ),
    ]
