# Generated by Django 2.2.13 on 2020-06-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0002_auto_20200514_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(verbose_name='release date'),
        ),
    ]
