# Generated by Django 2.2.13 on 2020-06-28 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0003_auto_20200628_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='images',
            new_name='image',
        ),
    ]
