# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-05 14:36
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0003_auto_20180105_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default=None, upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
