# Generated by Django 2.0.5 on 2018-05-05 17:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0004_auto_20180505_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete='', related_name='comments', to='flow.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.OneToOneField(on_delete='', to=settings.AUTH_USER_MODEL),
        ),
    ]
