# Generated by Django 2.2.13 on 2020-08-15 17:19

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0005_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='public',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='public',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(default='Belgrade', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='44.815971791260516,20.46053409576416', max_length=63),
        ),
    ]
