# Generated by Django 2.0.5 on 2018-05-06 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0005_auto_20180505_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='flow.Image'),
        ),
    ]
