# Generated by Django 2.0.5 on 2018-07-29 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0006_auto_20180506_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(upload_to='flow/static/images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow.Image'),
        ),
    ]
