# Generated by Django 2.2.13 on 2020-08-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0006_auto_20200815_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='show_map',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
