# Generated by Django 2.2.13 on 2020-08-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0008_auto_20200822_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
