# Generated by Django 2.0.5 on 2019-05-05 11:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0010_poem_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 5, 11, 12, 33, 712534, tzinfo=utc)),
        ),
    ]
