# Generated by Django 2.0.5 on 2019-11-17 16:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0011_auto_20190505_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='poem',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
