# Generated by Django 2.2.8 on 2020-01-16 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flow', '0014_auto_20191117_1957'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='post',
        #     name='author',
        # ),
        # migrations.AddField(
        #     model_name='post',
        #     name='author',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        # ),
    ]
